<#
  .SYNOPSIS
  Performs a synchronization of applications from the Micrsoft Endpoint Configuration Manager environment to your Intune environment utilizing REST APIs from both.

.DESCRIPTION
  Applications are marked as included/excluded using RegEx patterns against the Administration Category, Publisher, and DisplayName. The identified applications then have their content
  prepared by the Microsoft Win32 Content Prep Tool. 
    Requirements
      - Repositories: PSGallery
      - PackageProviders: NuGet
      - Modules: Microsoft.Graph.Authentication, Microsoft.Graph.Intune, Microsoft.Graph.Devices.CorporateManagement
      - GraphScopes: DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All

    Process
      #TODO: Add process overview

.PARAMETER Source
  Specify the source the synchronization process should use as the authoritative source for applications. All settings will be synchronized to match the source.

.PARAMETER SMSProvider
  Provide the FQDN of an SMS Provider in your MECM hierarchy.

.PARAMETER AdminCategory
  An array of RegEx patterns to identify the Applications to include based on the matching Administrative Category they have assigned.

.PARAMETER IntunePrepToolPath
  A path to the Microsoft Win32 Content Prep Tool (IntuneWinAppUtil.exe)

.PARAMETER Include
  An array of RegEx patterns to filter in the included applications. Only matching items are included. Blank is equal to 'include all'.

.PARAMETER Exclude
  An array of RegEx patterns to filter out the excluded applications. Everything but the matching items will be included. 'blank' is equal to 'exclude all', '^$' is equal to 'exclude none'.

.PARAMETER GraphModules
  Specify which modules of the Graph API PowerShell SDK are installed during execution of the script. All installs the parent Microsoft.Graph and all descendants. Required installs only those required by this script's function.

.PARAMETER OutputDir
  Path to the Directory for storing the log and output data from this script. No trailing slash needed.

.PARAMETER OutputName
  A name to use for the output log file so that it is easily identified as belonging to this process.

.PARAMETER Mode
Define the mode that the script will execute in. Analyze: source and target and output data without making chagnes. Execute: perform all analysis and make changes.

.PARAMETER Logging
Define the level of logging that is output to the console and the transcript log that is generated by the script.

.INPUTS
  None. Piping is not supported.

.OUTPUTS
  Return: No objects or data are returned from the script
  Files: A transcript log file as well as all datasets are output to the directory specified within the OutputDir parameter.

.EXAMPLE
PS> '.\Applications - Synchronize MECM Applications to Intune.ps1' -Param
Utilizes interactive authentication (recommended for testing)

.EXAMPLE
PS> '.\Applications - Synchronize MECM Applications to Intune.ps1' -Param
Utilizes service principal authentication (recommended for automation)

.LINK
  https://github.com/dustinestes/Intune_Toolkit

.COMPONENT
  NuGet Provider: This script installs the provider as a prerequisite to installing any of the Microsoft Graph APIs
  Required Graph PowerShell Modules
    - Microsoft.Graph.Authentication

.NOTES
  Interactive Authentication (Default)
    - This method will prompt for credentials and use the Microsoft Authentication Library (MSAL) to handle the authentication flow
    - No parameters required
    - Usage: .\Authentication.ps1
  
  Service Principal Authentication
    - This method uses an Azure AD App Registration with client credentials
    - Requires TenantId, ClientId, and ClientSecret
    - Usage: .\Authentication.ps1 -TenantId "your-tenant-id" -ClientId "your-client-id" -ClientSecret "your-client-secret"
  
  The script includes:
    - Automatic installation of the required Microsoft.Graph.Authentication module
    - Error handling and connection verification
    - Detailed output of the connection status and context
    - Support for custom scopes (defaults to https://graph.microsoft.com/.default)
#>

#--------------------------------------------------------------------------------------------
# Parameters
#--------------------------------------------------------------------------------------------

[CmdletBinding(SupportsShouldProcess=$true)]
param (
  [Parameter(Mandatory=$false, HelpMessage="Specify the source the synchronization process should use as the authoritative source for applications. All settings will be synchronized to match the source.")]
  [ValidateSet("MECM","Intune")]
    [array]$Source="MECM",
  [Parameter(Mandatory=$true, HelpMessage="Provide the FQDN of an SMS Provider in your MECM hierarchy.")]
    [string]$SMSProvider,
  [Parameter(Mandatory=$true, HelpMessage="An array of RegEx patterns to identify the Applications to include based on the matching Administrative Category they have assigned.")]
    [string]$AdminCategory,
  [Parameter(Mandatory=$true, HelpMessage="A path to the Microsoft Win32 Content Prep Tool (IntuneWinAppUtil.exe)")]
    [string]$IntunePrepToolPath,
  [Parameter(Mandatory=$false, HelpMessage="An array of RegEx patterns to filter in the included applications. Only matching items are included. Blank is equal to 'include all'.")]
    [array]$Include,
  [Parameter(Mandatory=$false, HelpMessage="An array of RegEx patterns to filter out the excluded applications. Everything but the matching items will be included. 'blank' is equal to 'exclude all', '^$' is equal to 'exclude none'.")]
    [array]$Exclude,

  [Parameter(Mandatory=$false, HelpMessage="Specify which modules of the Graph API PowerShell SDK are installed during execution of the script. All installs the parent Microsoft.Graph and all descendants. Required installs only those required by this script's function.")]
  [ValidateSet("All","Required")]
    [array]$GraphModules="Required",
  

  #TODO: Add in parameter sets for interactive and service principal auth
  [Parameter(Mandatory=$false, HelpMessage="Azure AD Tenant ID")]
    [string]$TenantId,
  [Parameter(Mandatory=$false, HelpMessage="Azure AD App Registration Client ID")]
    [string]$ClientId,
  [Parameter(Mandatory=$false, HelpMessage="Azure AD App Registration Client Secret")]
    [string]$ClientSecret,
  # [Parameter(Mandatory=$false, HelpMessage="Required permissions")]
  #   [string[]]$Scopes = @("https://graph.microsoft.com/.default"),

  [Parameter(Mandatory=$true, HelpMessage="Path to the Directory for storing the log and output data from this script. No trailing slash needed.")]
    [string]$OutputDir,
  [Parameter(Mandatory=$true, HelpMessage="A name to use for the output log file so that it is easily identified as belonging to this process.")]
    [string]$OutputName,
  [Parameter(Mandatory=$false, HelpMessage="Define the mode that the script will execute in. Analyze: source and target and output data without making chagnes. Execute: perform all analysis and make changes.")]
  [ValidateSet("Analyze","Execute")]
    [string]$Mode="Analyze",
  [Parameter(Mandatory=$false, HelpMessage="Define the level of logging that is output to the console and the transcript log that is generated by the script.")]
  [ValidateSet("Info","Debug","ErrorOnly")]
    [string]$Logging="Info"
)

#--------------------------------------------------------------------------------------------
Start-Transcript -Path "Filesystem::$($OutputDir)\$($OutputName).log" -ErrorAction SilentlyContinue

#--------------------------------------------------------------------------------------------
# Header
#--------------------------------------------------------------------------------------------
#Region Header

  Write-Host "------------------------------------------------------------------------------"
  Write-Host "  Intune Toolkit - Applications - Synchronize MECM Applications to Intune"
  Write-Host "------------------------------------------------------------------------------"
  Write-Host "    Author:     Dustin Estes"
  Write-Host "    Company:    VividRock"
  Write-Host "    Date:       2025-05-11"
  Write-Host "    Copyright:  VividRock LLC - All Rights Reserved"
  Write-Host "    Purpose:    This script queries the MECM database for applications that match"
  Write-Host "                the include/exclude criteria, prepares the content, and creates"
  Write-Host "                the application in Intune using the Microsoft Graph API."
  Write-Host "    Links:      https://learn.microsoft.com/en-us/intune/intune-service/apps/apps-win32-prepare"
  Write-Host "------------------------------------------------------------------------------"
  Write-Host ""

#EndRegion Header
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Variables
#   Error Range: 1100 - 1199
#--------------------------------------------------------------------------------------------
#Region Variables

  Write-Host "  Variables"

  # Parameters
  $Param_Source               = $Source
  $Param_SMSProvider          = $SMSProvider
  $Param_AdminCategory        = $AdminCategory
  $Param_IntunePrepToolPath   = $IntunePrepToolPath
  $Param_Include              = $Include
  $Param_Exclude              = $Exclude
  $Param_GraphModules         = $GraphModules
  $Param_OutputDir            = $OutputDir
  $Param_OutputName           = $OutputName
  $Param_Mode                 = $Mode
  $Param_Logging              = $Logging

  # Metadata
  $Meta_Script_Start_DateTime     = Get-Date
  $Meta_Script_Complete_DateTime  = $null
  $Meta_Script_Complete_TimeSpan  = $null
  $Meta_Script_Execution_User     = [System.Security.Principal.WindowsIdentity]::GetCurrent()
  $Meta_Script_Result             = $false,"Failure"

  # Preferences
  $ErrorActionPreference  = "Stop"

  # Requirements
  $Requirements = @{
    Repositories      = @(
      "PSGallery"
    )
    PackageProviders  = @(
      "NuGet"
    )
    Modules           = @(
      "Microsoft.Graph.Authentication"
      "Microsoft.Graph.Intune",
      "Microsoft.Graph.Devices.CorporateManagement"
    )
    GraphScopes       = @(
      "DeviceManagementApps.Read.All"
      # "DeviceManagementApps.ReadWrite.All"
    )
  }

  # Names

  # Paths
  $Path_IntunePrepTool  = $Param_IntunePrepToolPath
  $Path_OutputDir       = $Param_OutputDir

  # APIs
  $API_Root_Graph  = "https://graph.microsoft.com/v1.0/"
  $API_Root_GraphBeta  = "https://graph.microsoft.com/beta/"
  $API_Root_MECM    = "https://$($Param_SMSProvider)/AdminService/wmi/"

  # Files

  # Hashtables

  # Arrays

  # Registry

  # WMI

  # Datasets
  $Dataset_Applications = @()

  # Patterns

  # Temporary

  # Output to Log
  Write-Host "    - Parameters"
  foreach ($Item in $PSBoundParameters.GetEnumerator()) {
    Write-Host "        $($Item.Key.PadRight(($PSBoundParameters.Keys | Measure-Object -Property Length -Maximum).Maximum + 1)): $($Item.Value)"
  }

  Write-Host "    - Complete"
  Write-Host ""

#EndRegion Variables
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Classes
#   Error Range: 1200 - 1299
#--------------------------------------------------------------------------------------------
#Region Classes

  Write-Host "  Classes"

  class Application {
    [String] $Publisher
    [String] $DisplayName
    [String] $Version
    [MECMApp] $MECM
    [IntuneApp] $Intune
    [IntunePrepTool] $IntunePrepTool
    [Bool] $Include
    [Array] $Rules
    [SyncState] $SyncState
    [Status] $Status
  }

  class AppConfig {
    [String] $Publisher
    [String] $DisplayName
    [String] $Version
    [String] $Description
    [String] $Icon
    [String] $InfromationUrl
    [String] $PrivacyUrl
    [Array] $Categories
  }

  class MECMApp : AppConfig {
    [Int] $Revision
    [DeploymentType[]] $DeploymentTypes
    [Deployment[]] $Deployments
    [MECMMeta] $Metadata
  }

  class IntuneApp : AppConfig {
    [Program] $Program
    [Object] $Assignments
    [Object] $Detection
    [IntuneMeta] $Metadata
  }

  class IntunePrepTool {
    [String] $CommandLine
    [Status] $Status
  }

  class DeploymentType {
    [String] $Id
    [Int] $Priority
    [String] $Name
    [String] $ModelName
    [String] $ContentID
    [String] $Context
    [MECMProgram] $Installation
    [MECMProgram] $Uninstallation
    [Detection] $Detection
  }
  
  class Program {
    # [String] $CommandLine
  }

  class MECMProgram {
    [String] $CommandLine
    [String] $WorkingDirectory
    [String] $RequiresLogOn
    [Bool] $RequiresElevatedRights
    [Bool] $RequiresUserInteraction
    [Bool] $RequiresReboot
    [String] $UserInteractionMode
    [String] $PostInstallBehavior
    [Int] $ExecuteTime
    [Int] $MaxExecuteTime
    [Bool] $RunAs32Bit
    [String] $ContentID
    [String] $ContentPath
    [Object] $ContentFile
  }

  class IntuneProgram : Program {
    [String] $InstallCommandLine
    [String] $UninstallCommandLine
    [String] $RunAs
    [String] $RestartBehavior
    [String] $ContentFile
    [String] $SetupFile
    [Int] $SetupFileSize
    [Object] $ReturnCodes
    [Object] $MSIInformation
  }

  class Content {
    [Object] $MSIInformation
    [String] $Filename
    [String] $Version
    [Int] $Size
  }
  
  class Detection {
    [String] $Provider
  }

  class ScriptDetection : Detection {
    [String] $Context
    [String] $ScriptType
    [String] $ScriptBody
    [Bool] $RunAs32Bit
  }

  $Trans_ScriptDetection_ScriptType = @{
    0 = "PowerShell"
    1 = "VBScript"
    2 = "JScript"
  }
  
  class Requirements {
    
  }
    
  class Deployment {

  }

  class ReturnCode {
    [Int] $ReturnCode
    [String] $Type
  }

  class Metadata {
    [String] $Id
    [DateTime] $Created
    [DateTime] $Modified
  }
  class MECMMeta : Metadata {
    [Array] $Owners
    [Array] $Contacts
    [String] $CreatedBy
    [String] $ModifiedBy
    [String] $ModelName
    [Bool] $IsLatest
    [Bool] $IsSuperseded
    [int] $DependentDTs
    [int] $Deployments
    [int] $DeploymentTypes
  }

  class IntuneMeta : Metadata {
    [String] $Owner
    [String] $Developer
    [String] $Notes
  }

  enum SyncState {
    Pending
    MatchFound
    NotSynced
    Synced
    NotExist
    Created
  }

  enum Status {
    Pending
    InProgress
    Success
    Error
    Skipped
  }

  Write-Host "    - Complete"
  Write-Host ""

#EndRegion Classes
#--------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------
# Functions
#   Error Range: 1300 - 1399
#--------------------------------------------------------------------------------------------
#Region Functions

  Write-Host "  Functions"

  # Write-HostFormat
  <#
  .SYNOPSIS
  Writes log output based on the type of the message passed to the function compared to the logging level set during script initialization.
  #>
  Write-Host "    - Write-HostFormat"
  function Write-HostFormat {
  [CmdletBinding(DefaultParameterSetName="Message")]
    param (
      [Parameter(Mandatory=$true, ParameterSetName="Message", HelpMessage="Message for logging.")]
      [string]$Message,
      [Parameter(Mandatory=$true, ParameterSetName="Object", HelpMessage="Message for logging.")]
      [object]$ErrorObject,
      [Parameter(Mandatory=$false, ParameterSetName="", HelpMessage="The log level type of the message.")]
      [ValidateSet("INFO","WARN","ERROR","FATAL","DEBUG")]
      [string]$Type="INFO",
      [Parameter(Mandatory=$false, ParameterSetName="", HelpMessage="Indent level that the message should be displayed at.")]
      [int]$Indent=0,
      [Parameter(Mandatory=$false, ParameterSetName="", HelpMessage="Adds a number of new lines after the last message written.")]
      [int]$NewLines=0,
      [Parameter(Mandatory=$false, ParameterSetName="", HelpMessage="A hashtable set of supported arguments to pass to the Write-Host cmdlet.")]
      [hashtable]$Arguments,
      [Parameter(Mandatory=$false, ParameterSetName="", HelpMessage="Exit code to return to the console and caller.")]
      [int]$ExitCode
    )

    begin {
      # Set Delimiter
      $Delimiter = "  "

      # Associate Log Types to Logging Level
      $LoggingLevels = @{
        Info      = @("INFO","WARN","ERROR","FATAL")
        Debug     = @("INFO","WARN","ERROR","FATAL","DEBUG")
        ErrorOnly = @("ERROR","FATAL")

      }
    }

    process {
      if ($Message) {
        # Construct Strings with Indent
        $Message = ($Delimiter * $Indent) + $Message
  
        # Output
        switch ($Param_Logging) {
          "Info" {
            if ($Type -in $LoggingLevels.Info) {
              Write-Host $Message @Arguments
            }
          }
          "Debug" {
            if ($Type -in $LoggingLevels.Debug) {
              Write-Host $Message
            }
          }
          "ErrorOnly" {
            if ($Type -in $LoggingLevels.ErrorOnly) {
              Write-Host $Message
            }
          }
          Default {}
        }
      }
      elseif ($ErrorObject) {
        # Construct Strings with Indent
        $Message    = ($Delimiter * $Indent) + "Message: " + $ErrorObject.Exception.Message
        $ErrorID    = ($Delimiter * $Indent) + "ErrorId: " + $ErrorObject.Exception.ErrorId
        $Activity   = ($Delimiter * $Indent) + "Activity: " + $ErrorObject.CategoryInfo.Activity
        $Location   = ($Delimiter * $Indent) + "Line/Position: " + $ErrorObject.Exception.Line + " / " + $ErrorObject.Exception.Offset
        $ScriptName = ($Delimiter * $Indent) + "ScriptName: " + $ErrorObject.InvocationInfo.ScriptName
  
        # Output
        Write-Host $Message
        Write-Host $ErrorID
        Write-Host $Activity
        Write-Host $Location
        Write-Host $ScriptName
      }
      else { }
    }

    end {
      # Process NewLines Parameter
      if ($NewLines -gt 0) {
        $Message = "`n" * ($NewLines - 1)
        Write-Host $Message
      }

      # Process Fatal Messages
      if (($Type = "FATAL") -and $ExitCode) {
        # Construct Strings with Indent
        $ExitMessage    = ($Delimiter * $Indent) + "ExitCode: " + $ExitCode

        # Output
        Write-Host $ExitMessage

        # Cleanup
        Stop-Transcript -ErrorAction SilentlyContinue
        Exit $ExitCode
      }
    }
  }

  # Write Error Codes
  Write-Host "    - Write-vr_ErrorCode"
  function Write-vr_ErrorCode ($Code,$Exit,$Object) {
    # Code: XXXX   4-digit code to identify where in script the operation failed
    # Exit: Boolean option to define if  exits or not
    # Object: The error object created when the script encounters an error ($Error[0], $PSItem, etc.)

    begin {

    }

    process {
      Write-Host "        Error: $($Object.Exception.ErrorId)"
      Write-Host "        Command Name: $($Object.CategoryInfo.Activity)"
      Write-Host "        Message: $($Object.Exception.Message)"
      Write-Host "        Line/Position: $($Object.Exception.Line)/$($Object.Exception.Offset)"
    }

    end {
      switch ($Exit) {
        $true {
          Write-Host "        Disconnect Microsoft Graph"
          if (Get-MgContext) {
            $Result = Disconnect-MgGraph
            Write-Host "        Account: $($Result.Account)"
            Write-Host "        TenantId: $($Result.TenantId)"
            Write-Host "        ClientId: $($Result.ClientId)"
            Write-Host "        Status: Success"
          }
          else {
            Write-Host "          Status: No Connection Found"
          }

          Write-Host "        Exit: $($Code)"
          Stop-Transcript -ErrorAction SilentlyContinue
          Exit $Code
        }
        $false {
          Write-Host "        Continue Processing..."
        }
        Default {
          Write-Host "        Unknown Exit option in Write-vr_ErrorCode parameter"
          
          Write-Host "        Disconnect Microsoft Graph"
          if (Get-MgContext) {
            $Result = Disconnect-MgGraph
            Write-Host "        Account: $($Result.Account)"
            Write-Host "        TenantId: $($Result.TenantId)"
            Write-Host "        ClientId: $($Result.ClientId)"
            Write-Host "        Status: Success"
          }
          else {
            Write-Host "          Status: No Connection Found"
          }
          Stop-Transcript -ErrorAction SilentlyContinue
          Exit 9999
        }
      }
    }
  }

  # Connect to Microsoft Graph
  # TODO: Revisit the use of this function when capabilities are handled well outside of it
  Write-Host "    - Connect-MsGraph"
  function Connect-MsGraph {
    [CmdletBinding()]
    param (
      [Parameter(Mandatory=$false, HelpMessage="Azure AD Tenant ID")]
      [string]$TenantId,
      [Parameter(Mandatory=$false, HelpMessage="Azure AD App Registration Client ID")]
      [string]$ClientId,
      [Parameter(Mandatory=$false, HelpMessage="Azure AD App Registration Client Secret")]
      [string]$ClientSecret,
      [Parameter(Mandatory=$false, HelpMessage="Required permissions")]
      [string[]]$Scopes
    )

    begin {

    }

    process {
      try {
        # Install Required Providers
        if (-not (Get-PackageProvider -ListAvailable -Name "NuGet")) {
          Write-Verbose "Installing the NuGet package provider"
          Install-PackageProvider -Name NuGet -Confirm:$false
          Import-PackageProvider -Name NuGet -Force
        }

        # Install Required Modules
        if (-not (Get-Module -ListAvailable -Name "Microsoft.Graph.Authentication")) {
          Write-Verbose "Installing the Microsoft.Graph.Authentication module"
          Install-Module -Name "Microsoft.Graph.Authentication" -Force -Scope CurrentUser
        }
  
        # Connect Using Interactive Authentication
        if (-not $TenantId -or -not $ClientId -or -not $ClientSecret) {
          Write-Verbose "Connecting to Microsoft Graph using interactive authentication..."
          Connect-MgGraph -Scopes $Scopes
        }
        # Connect Using Service Principal Authentication
        else {
          Write-Verbose "Connecting to Microsoft Graph using service principal authentication..."
          $SecureSecret = ConvertTo-SecureString -String $ClientSecret -AsPlainText -Force
          $Credential = New-Object System.Management.Automation.PSCredential($ClientId, $SecureSecret)
          Connect-MgGraph -TenantId $TenantId -ClientId $ClientId -ClientSecretCredential $Credential
        }
  
          # Verify connection
          $Context = Get-MgContext
          if ($Context) {
            Write-Verbose "Successfully connected to Microsoft Graph API"
            Write-Verbose "Tenant ID: $($Context.TenantId)"
            Write-Verbose "Account: $($Context.Account)"
            Write-Verbose "Scopes: $($Context.Scopes -join ', ')"
            return $Context
          }
          else {
            throw "Failed to establish connection to Microsoft Graph API"
          }
      }
      catch {
        Write-Error "Error connecting to Microsoft Graph API: $_"
        return $false
      }
    }

    end {

    }
  }

  # Invoke-MgGraphRequestPaginated
  Write-Host "    - Invoke-MgGraphRequestPaginated"
  function Invoke-MgGraphRequestPaginated {
  <#
  .SYNOPSIS
  Queries the Graph API using a paginated request format to gather all data possible from the URL
  .EXAMPLE
  Invoke-MGGraphRequestPaginated -Uri
  #>
  [CmdletBinding()]
    param (
      [Parameter(Mandatory=$false, HelpMessage="HTTP Method")]
      [string]$Method="GET",
      [Parameter(Mandatory=$true, HelpMessage="Microsoft Graph API Url to query for data")]
      [string]$Uri,
      [Parameter(Mandatory=$false, HelpMessage="Custom Content Type")]
      [string]$ContentType,
      [Parameter(Mandatory=$false, HelpMessage="Microsoft Graph API Url to query for data")]
      [ValidateSet("HashTable","PSObject","HttpResponseMessage", "Json")]
      [string]$OutputType="PsObject"
      # [Parameter(ValueFromRemainingArguments=$true)]
      # [object[]]$Args
    )

    begin {

    }

    process {
      try {
        $Response = (Invoke-MgGraphRequest -uri $Uri -Method Get -OutputType PSObject)
        $Dataset = $Response.value
        $NextLink = $Response."@odata.nextLink"
        
        while ($null -ne $NextLink) {
            $Response_Sub = (Invoke-MGGraphRequest -Uri $NextLink_Sub -Method Get -OutputType PSObject)
            $NextLink_Sub = $Response_Sub."@odata.nextLink"
            $Dataset += $Response_Sub.value
        }
      }
      catch {
        Throw "Error: $($_.Exception.Message)"
        return $false
      }
    }

    end {
      Return $Dataset
    }
  }

  Write-Host "    - Complete"
  Write-Host ""

#EndRegion Functions
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Environment
#   Error Range: 1400 - 1499
#--------------------------------------------------------------------------------------------
#Region Environment

  Write-HostFormat -Message "Environment" -Type INFO -Indent 1

  # Define Trusted PowerShell Repositories
  Write-HostFormat -Message "- Define Trusted PowerShell Repositories" -Type INFO -Indent 2

  try {
    foreach ($Item in $Requirements.Repositories) {
      Write-HostFormat -Message "Repository: $($Item)" -Type INFO -Indent 4

      if ((Get-PSRepository -Name "PSGallery").InstallationPolicy -ne "Trusted") {
        Set-PSRepository -Name $Item -InstallationPolicy Trusted
        Write-HostFormat -Message "Status: Added Trust" -Type INFO -Indent 5
      }
      else {
        Write-HostFormat -Message "Status: Already Trusted" -Type INFO -Indent 5
      }
    }
	}
	catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1401
	}
  finally {
    # Cleanup Variables
    Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
    # Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
  }
  
  # Install PowerShell Package Providers
  Write-HostFormat -Message "- Install PowerShell Package Providers" -Type INFO -Indent 2

  try {
    foreach ($Item in $Requirements.PackageProviders) {
      Write-HostFormat -Message "Provider: $($Item)" -Type INFO -Indent 4
      if (Get-PackageProvider -Name $Item -ErrorAction SilentlyContinue) {
        Write-HostFormat -Message "Status: Exists" -Type INFO -Indent 5
      }
      else {
        Install-PackageProvider -Name $Item -Confirm:$false -Scope CurrentUser -Force
        Import-PackageProvider -Name $Item -Force
        Write-HostFormat -Message "Status: Installed" -Type INFO -Indent 5
      }
    }
	}
	catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1402
	}
  finally {
    # Cleanup Variables
    Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
    # Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
  }

  # Install PowerShell Modules
  Write-HostFormat -Message "- Install PowerShell Modules" -Type INFO -Indent 2

  try {
    switch ($Param_GraphModules) {
      "All" {
        Write-HostFormat -Message "Module: Microsoft.Graph" -Type INFO -Indent 4
        if (Get-InstalledModule -Name "Microsoft.Graph") {
          Write-HostFormat -Message "Status: Exists" -Type INFO -Indent 5
        }
        else {
          Install-Module -Name "Microsoft.Graph" -Scope CurrentUser -AllowClobber -Force
          Write-HostFormat -Message "Status: Installed" -Type INFO -Indent 5
        }
      }
      "Required" {
        foreach ($Item in $Requirements.Modules) {
          Write-HostFormat -Message "Module: $($Item)" -Type INFO -Indent 4
          if (Get-InstalledModule -Name $Item) {
            Write-HostFormat -Message "Status: Exists" -Type INFO -Indent 5
          }
          else {
            Install-Module -Name $Item -Scope CurrentUser -Force
            Write-HostFormat -Message "Status: Installed" -Type INFO -Indent 5
          }
        }
      }
      Default { Throw "An unsupported value was provided for the GraphModules parameter. Please check the documentation for supported values." }
    }
	}
	catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1403
	}
  finally {
    # Cleanup Variables
    Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
    # Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
  }

  # Connect to Microsoft Graph API
  Write-HostFormat -Message "- Connect to Microsoft Graph API" -Type INFO -Indent 2

  try {
    $Temp_MgGraph = Connect-MsGraph -TenantId $TenantId -ClientId $ClientId -ClientSecret $ClientSecret -Scopes $Scopes
    
    if ($Temp_MgGraph) {
      Write-HostFormat -Message "Account: $($Temp_MgGraph.Account)" -Type INFO -Indent 4
      Write-HostFormat -Message "TenantId: $($Temp_MgGraph.TenantId)" -Type INFO -Indent 4
      Write-HostFormat -Message "ClientId: $($Temp_MgGraph.ClientId)" -Type INFO -Indent 4
      Write-HostFormat -Message "Scopes: $($Temp_MgGraph.Scopes)" -Type INFO -Indent 4
      Write-HostFormat -Message "Status: Success" -Type INFO -Indent 4
    }
    else {
      Write-HostFormat -Message "A connection to the Microsoft Graph API could not be established." -Type FATAL -Indent 5 -ExitCode 1404
    }
  }
  catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1404
  }
  finally {
    # Cleanup Variables
    Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
    Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
  }  

  Write-HostFormat -Message "- Complete" -Type INFO -Indent 2 -NewLines 1

#EndRegion Environment
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Validation
#   Error Range: 1500 - 1599
#--------------------------------------------------------------------------------------------
#Region Validation

  Write-HostFormat -Message "Validation" -Type INFO -Indent 1

  # API Roots
  Write-HostFormat -Message "- API Roots" -Type INFO -Indent 2

  try {
    foreach ($Item in (Get-Variable -Name "API_Root_*")) {
      Write-HostFormat -Message "Route: $($Item.Value)" -Type INFO -Indent 4

      if (Invoke-RestMethod -Uri $Item.Value -Method Get -ContentType "Application/Json" -UseDefaultCredentials) {
        Write-HostFormat -Message "Status: Success" -Type INFO -Indent 5
      }
      else {
        Write-HostFormat -Message "Status: Error" -Type INFO -Indent 5
        Throw
      }
    }
  }
  catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1501
  }
  finally {
    # Cleanup Variables
    Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
    # Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
  }

	# Paths
  Write-HostFormat -Message "- Paths" -Type INFO -Indent 2

  try {
    foreach ($Item in (Get-Variable -Name "Path_*")) {
      Write-HostFormat -Message "Path: $($Item.Value)" -Type INFO -Indent 4

      if (Test-Path -Path "filesystem::$($Item.Value)") {
        Write-HostFormat -Message "Status: Exists" -Type INFO -Indent 5
      }
      else {
        New-Item -Path $Item.Value -ItemType Directory -Force | Out-Null
        Write-HostFormat -Message "Status: Created" -Type INFO -Indent 5
      }
    }
  }
  catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1502
  }
  finally {
    # Cleanup Variables
    Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
    # Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
  }

	# Required Graph Scopes
  Write-HostFormat -Message "- Required Graph Scopes" -Type INFO -Indent 2

  try {
    $Temp_MgContext = Get-MgContext
    foreach ($Item in $Requirements.GraphScopes) {
      Write-HostFormat -Message "Scope: $($Item)" -Type INFO -Indent 4

      if ($Temp_MgContext.Scopes -contains $Item) {
        Write-HostFormat -Message "Status: Exists" -Type INFO -Indent 5
      }
      else {
        Write-HostFormat -Message "The required scope: $($Item) is not granted to the account: $($Temp_MgContext.Account)" -Type FATAL -Indent 5 -ExitCode 1503
      }
    }
  }
  catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1503
  }
  finally {
    # Cleanup Variables
    Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
    # Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
  }

	Write-HostFormat -Message "- Complete" -Type INFO -Indent 2 -NewLines 1

#EndRegion Validation
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Data Gather
#   Error Range: 1600 - 1699
#--------------------------------------------------------------------------------------------
#Region Data Gather

  Write-HostFormat -Message "Data Gather" -Type INFO -Indent 1  

  # MECM - Get Applications
  Write-HostFormat -Message "- MECM - Get Applications" -Type INFO -Indent 2

  try {
    $API_Route = "SMS_Application"
    $API_Filter = "?`$Select=CI_ID,Manufacturer,LocalizedDisplayName,SoftwareVersion,LocalizedCategoryInstanceNames,ModelName,IsLatest,IsSuperseded,DateCreated,CreatedBy,DateLastModified,LastModifiedBy,NumberOfDependentDTs,NumberOfDeployments,NumberOfDeploymentTypes&`$filter=IsLatest eq true"
      # Add Admin Category Filter Query if Specified
      if ($Param_AdminCategory) {
        $API_Filter = $API_Filter + " and LocalizedCategoryInstanceNames/any(item: item eq '$($Param_AdminCategory)')"
      }
    Write-HostFormat -Message "Route: $($API_Root_MECM)$($API_Route)" -Type DEBUG -Indent 4
    Write-HostFormat -Message "Filter: $($API_Filter)" -Type DEBUG -Indent 4
    $Temp_MECM_Applications = (Invoke-RestMethod -Uri "$($API_Root_MECM)$($API_Route)$($API_Filter)" -Method Get -ContentType "Application/Json" -UseDefaultCredentials).value
    Write-HostFormat -Message "Count: $($Temp_MECM_Applications.Count)" -Type INFO -Indent 4
  }
  catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1601
  }
  finally {
    # Cleanup Variables
  }

  # Intune - Get Applications
  Write-HostFormat -Message "- Intune - Get Applications" -Type INFO -Indent 2

  try {
    $API_Route  = "deviceAppManagement/mobileApps"
    $API_Filter = "?`$filter=(isof('microsoft.graph.win32LobApp'))&`$expand=*"
    Write-HostFormat -Message "Route: $($API_Root_GraphBeta)$($API_Route)" -Type DEBUG -Indent 4
    Write-HostFormat -Message "Filter: $($API_Filter)" -Type DEBUG -Indent 4
    $Temp_Intune_Applications = (Invoke-MgGraphRequest -Uri "$($API_Root_GraphBeta)$($API_Route)$($API_Filter)" -Method GET -OutputType PSObject).value
    Write-HostFormat -Message "Count: $($Temp_Intune_Applications.Count)" -Type INFO -Indent 4
  }
  catch {
    Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1602
  }
  finally {
    # Cleanup Variables
  }

  # Initialize Dataset
  Write-HostFormat -Message "- Initialize Dataset" -Type INFO -Indent 2

  switch ($Param_Source) {
    "MECM" {
      foreach ($Item in $Temp_MECM_Applications) {
        try {
          # Construct Basic Object
          $Temp_Object = [Application]@{
            Publisher     = $Item.Manufacturer
            DisplayName   = $Item.LocalizedDisplayName
            Version       = $Item.SoftwareVersion
            MECM = [MECMApp]@{
              Publisher     = "[ToBeConfiguredLater]"
              DisplayName   = "[ToBeConfiguredLater]"
              Version       = "[ToBeConfiguredLater]"
              Metadata = [MECMMeta]@{
                Id                        = $Item.CI_ID
                ModelName                 = $Item.ModelName
                IsLatest                  = $Item.IsLatest
                IsSuperseded              = $Item.IsSuperseded
                Created                   = $Item.DateCreated
                CreatedBy                 = $Item.CreatedBy
                Modified                  = $Item.DateLastModified
                ModifiedBy                = $Item.LastModifiedBy
                DependentDTs              = $Item.NumberOfDependentDTs
                Deployments               = $Item.NumberOfDeployments
                DeploymentTypes           = $Item.NumberOfDeploymentTypes
              }
              Categories    = $Item.LocalizedCategoryInstanceNames
            }
            Include = $false
          }

          # Add to Dataset
          $Dataset_Applications += $Temp_Object
        }
        catch {
          Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 4 -ExitCode 1603
        }
        finally {
          # Cleanup Variables
          Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
        }
      }

      Write-HostFormat -Message "Status: Success" -Type INFO -Indent 4
    }
    "Intune" {
      # TODO: Add logic for Intune source route
    }
    Default {
      Write-HostFormat -Message "An unsupported value was provided for the Source parameter. Please check the documentation for supported values." -Type FATAL -Indent 5 -ExitCode 1603
    }
  }

  # Filter - Inclusion/Exclusion Rules
  Write-HostFormat -Message "- Filter - Inclusion/Exclusion Rules" -Type INFO -Indent 2

  foreach ($Item in $Dataset_Applications) {
    try {
      # IsSuperseded = True
      if ($Item.MECM.Metadata.IsSuperseded) {
        $Item.Rules += "IsSuperseded = True"
      }

      # NumberOfDeploymentTypes = 0
      if ($Item.MECM.Metadata.DeploymentTypes -eq 0) {
        $Item.Rules += "NumberOfDeploymentTypes = 0"
      }

      # Administrative Category Matches
      if ($Param_AdminCategory -in "",$null) {
        # Skip Because This Will Include All
      }
      elseif (-not ($Param_AdminCategory -in $Item.MECM.Categories)) {
          $Item.Rules += "Administrative Category Not Matched"
      }

      # Both Names Do Not Match Include Pattern
      if (($Item.Publisher -notmatch ($Param_Include -join "|")) -and ($Item.DisplayName -notmatch [regex]::Escape($Param_Include -join "|")) -and ($Item.DisplayName -ne ($Param_Include -join "|"))) {
        $Item.Rules += "Include Pattern Not Match"
      }

      # Either Names Match Exclude Pattern
      if (($Item.Publisher -match ($Param_Exclude -join "|")) -or ($Item.DisplayName -match ($Param_Exclude -join "|")) -or ($Item.DisplayName -eq ($Param_Exclude -join "|"))) {
        $Item.Rules += "Exclude Pattern Match"
      }

      # Application Already in Intune
      #TODO: Add logic for determining and filtering items that match this criter

      # Final Analysis
      if ($Item.Rules -in "",$null) {
        $Item.Include = $true
        $Item.Rules += "All Rules Passed"
        $Item.Status = "Pending"
      }
      else {
        $Item.Include = $false
        $Item.Status = "Skipped"
      }

      # Write-Host "          Status: Success"
    }
    catch {
      Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 4 -ExitCode 1604
    }
  }
  Write-HostFormat -Message "Included: $(($Dataset_Applications | Where-Object {$_.Include -eq $true} | Measure-Object).Count)" -Type INFO -Indent 4
  Write-HostFormat -Message "Excluded: $(($Dataset_Applications | Where-Object {$_.Include -eq $false} | Measure-Object).Count)" -Type INFO -Indent 4
  Write-HostFormat -Message "Total: $(($Dataset_Applications | Measure-Object).Count)" -Type INFO -Indent 4
  Write-HostFormat -Message "Status: Success" -Type INFO -Indent 4

  # Join MECM & Intune Datasets
  Write-HostFormat -Message "- Join MECM & Intune Datasets" -Type INFO -Indent 2
  switch ($Param_Source) {
    "MECM" {
      foreach ($Item in ($Dataset_Applications | Where-Object -FilterScript {$_.Include -eq $true})) {
        try {
          # Find Intune Match (If Exist)
          $Temp_Match = $Temp_Intune_Applications | Where-Object { (($Item.Publisher -match [regex]::Escape($_.publisher)) -or ($_.publisher -match [regex]::Escape($Item.Publisher))) -and (($Item.DisplayName -match [regex]::($_.displayName)) -or ($_.displayName -match [regex]::Escape($Item.DisplayName))) -and ($Item.Version -eq $_.displayVersion)}

          if ($Temp_Match) {
            # Update SyncState
            $Item.SyncState = "MatchFound"

            # Add Data to Object
            $Item.Intune = [IntuneApp]@{
              Publisher       = $Temp_Match.publisher
              DisplayName     = $Temp_Match.displayName
              Version         = $Temp_Match.displayVersion
              Description     = $Temp_Match.descripton
              Icon            = $Temp_Match.largeIcon
              InfromationUrl  = $Temp_Match.informationUrl
              PrivacyUrl      = $Temp_Match.privacyInformationUrl
              Categories      = @()
              Program = [IntuneProgram]@{
                InstallCommandLine    = $Temp_Match.installCommandLine
                UninstallCommandLine  = $Temp_Match.uninstallCommandLine
                RunAs                 = $Temp_Match.installExperience.runAsAccount
                RestartBehavior       = $Temp_Match.installExperience.deviceRestartBehavior
                ContentFile           = $Temp_Match.fileName
                SetupFile             = $Temp_Match.setupFilePath
                SetupFileSize         = $Temp_Match.size
                ReturnCodes           = $Temp_Match.returnCodes
                MSIInformation        = $Temp_Match.msiInformation
              }
              Assignments = $Temp_Match.assignments
              Detection = $Temp_Match.rules
              Metadata = [IntuneMeta]@{
                Id          = $Temp_Match.id
                Created     = $Temp_Match.createdDateTime
                Modified    = $Temp_Match.lastModifiedDateTime
                Owner       = $Temp_Match.owner
                Developer   = $Temp_Match.developer
                Notes       = $Temp_Match.notes
              }
            }
          }
          else {
            # Update SyncState
            $Item.SyncState = "NotExist"
          }
        }
        catch {
          Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 4 -ExitCode 1605
        }
        finally {
          # Cleanup Variables
          Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
          Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
        }
      }

      Write-HostFormat -Message "Matches: $(($Dataset_Applications | Where-Object {$_.SyncState -eq "MatchFound"} | Measure-Object).Count)" -Type INFO -Indent 4
    }
    "Intune" {
      # TODO: Add logic for Intune source route
    }
    Default {
      Write-HostFormat -Message "An unsupported value was provided for the Source parameter. Please check the documentation for supported values." -Type FATAL -Indent 5 -ExitCode 1604
    }
  }

  # Add MECM Data Subsets
  Write-HostFormat -Message "- Add MECM Data Subsets" -Type INFO -Indent 2

  foreach ($Item in ($Dataset_Applications | Where-Object -FilterScript {$_.Include -eq $true})) {
    Write-HostFormat -Message "$($Item.Publisher) - $($Item.DisplayName) - $($Item.Version)" -Type INFO -Indent 4
    try {
      # Get Application XML Data
      Write-HostFormat -Message "Source: Application XML Data" -Type DEBUG -Indent 5
      $API_Route = "SMS_Application/$($Item.MECM.Metadata.Id)"
      $API_Filter = ""
      Write-HostFormat -Message "Route: $($API_Root_MECM)$($API_Route)" -Type DEBUG -Indent 6
      Write-HostFormat -Message "Filter: $($API_Filter)" -Type DEBUG -Indent 6
      $Temp_SDMPackageXML = ([xml](Invoke-RestMethod -Uri "$($API_Root_MECM)$($API_Route)$($API_Filter)" -Method Get -ContentType "Application/Json" -UseDefaultCredentials).value.SDMPackageXML).AppMgmtDigest

      # Add Data to Object
      $Item.MECM.Revision           = $Temp_SDMPackageXML.Application.Version
      $Item.MECM.Publisher          = $Temp_SDMPackageXML.Application.Publisher.InnerText
      $Item.MECM.DisplayName        = $Temp_SDMPackageXML.Application.Title.InnerText
      $Item.MECM.Version            = $Temp_SDMPackageXML.Application.SoftwareVersion.InnerText
      $Item.MECM.Metadata.Owners    = $Temp_SDMPackageXML.Application.Owners.User.ID -join ","
      $Item.MECM.Metadata.Contacts  = $Temp_SDMPackageXML.Application.Contacts.User.ID -join ","

      # Get Deployment Type Details
      Write-HostFormat -Message "Source: Deployment Type Details" -Type DEBUG -Indent 5

      if ($Item.MECM.Metadata.DeploymentTypes -gt 0) {
        # Get Valid Deployment Types (Latest Revision)
        $API_Route = "SMS_DeploymentType"
        $API_Filter = "?`$filter=AppModelName eq `'$($Item.MECM.Metadata.ModelName)`' and IsLatest eq true &`$select=CI_ID,PriorityInLatestApp,LocalizedDisplayName,ModelName,ContentId"
        Write-HostFormat -Message "Route: $($API_Root_MECM)$($API_Route)" -Type DEBUG -Indent 6
        Write-HostFormat -Message "Filter: $($API_Filter)" -Type DEBUG -Indent 6
        $Temp_DTs = (Invoke-RestMethod -Uri "$($API_Root_MECM)$($API_Route)$($API_Filter)" -Method Get -ContentType "Application/Json" -UseDefaultCredentials).Value

        # Add Data to Object
        foreach ($Temp_DT in $Temp_DTs) {
          $Temp_DT_XML = ([xml](Invoke-RestMethod -Uri "$($API_Root_MECM)$($API_Route)/$($Temp_DT.CI_ID)" -Method Get -ContentType "Application/Json" -UseDefaultCredentials).value.SDMPackageXML).AppMgmtDigest
          $Temp_DT_XML_Sub =  $Temp_DT_XML.DeploymentType | Where-Object {$_.LogicalName -eq ($Temp_DT.ModelName -split "/")[1]}
          # Construct Deployment Type Object

          # Add to Application Object
          $Item.MECM.DeploymentTypes += [DeploymentType]@{
            Id                = $Temp_DT.CI_ID
            Priority          = $Temp_DT.PriorityInLatestApp
            Name              = $Temp_DT.LocalizedDisplayName
            ModelName         = $Temp_DT.ModelName
            ContentID         = $Temp_DT.ContentId
            Context           = $Temp_DT_XML.DeploymentType.Installer.ExecutionContext
            Installation      = [MECMProgram]@{
              CommandLine             = ($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "InstallCommandLine"}).InnerText
              WorkingDirectory        = ($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "WorkingDirectory"}).InnerText
              RequiresLogOn           = ($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresLogOn"}).InnerText
              RequiresElevatedRights  = if (($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresElevatedRights"}).InnerText -eq "true") {$true} else {$false}
              RequiresUserInteraction = if (($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresUserInteraction"}).InnerText -eq "true") {$true} else {$false}
              RequiresReboot          = if (($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresReboot"}).InnerText -eq "true") {$true} else {$false}
              UserInteractionMode     = ($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "UserInteractionMode"}).InnerText
              PostInstallBehavior     = ($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "PostInstallBehavior"}).InnerText
              # ExecuteTime             = ($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "ExecuteTime"}).InnerText
              # MaxExecuteTime          = ($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "MaxExecuteTime"}).InnerText
              RunAs32Bit              = if (($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "RunAs32Bit"}).InnerText -eq "true") {$true} else {$false}
              ContentID               = ($Temp_DT_XML_Sub.Installer.Contents.Content | Where-Object {$_.ContentId -eq ($Temp_DT_XML_Sub.Installer.InstallAction.Contents.Content.ContentId)}).ContentId
              ContentPath             = ($Temp_DT_XML_Sub.Installer.Contents.Content | Where-Object {$_.ContentId -eq ($Temp_DT_XML_Sub.Installer.InstallAction.Contents.Content.ContentId)}).Location
              ContentFile             = ($Temp_DT_XML_Sub.Installer.Contents.Content | Where-Object {$_.ContentId -eq ($Temp_DT_XML_Sub.Installer.InstallAction.Contents.Content.ContentId)}).File
            }
            Uninstallation    = [MECMProgram]@{
              CommandLine             = ($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "InstallCommandLine"}).InnerText
              WorkingDirectory        = ($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "WorkingDirectory"}).InnerText
              RequiresLogOn           = ($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresLogOn"}).InnerText
              RequiresElevatedRights  = if (($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresElevatedRights"}).InnerText -eq "true") {$true} else {$false}
              RequiresUserInteraction = if (($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresUserInteraction"}).InnerText -eq "true") {$true} else {$false}
              RequiresReboot          = if (($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "RequiresReboot"}).InnerText -eq "true") {$true} else {$false}
              UserInteractionMode     = ($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "UserInteractionMode"}).InnerText
              PostInstallBehavior     = ($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "PostInstallBehavior"}).InnerText
              # ExecuteTime             = ($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "ExecuteTime"}).InnerText
              # MaxExecuteTime          = ($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "MaxExecuteTime"}).InnerText
              RunAs32Bit              = if (($Temp_DT_XML_Sub.Installer.UninstallAction.Args.Arg | Where-Object {$_.Name -eq "RunAs32Bit"}).InnerText -eq "true") {$true} else {$false}
              ContentID               = ($Temp_DT_XML_Sub.Installer.Contents.Content | Where-Object {$_.ContentId -eq ($Temp_DT_XML_Sub.Installer.UninstallAction.Contents.Content.ContentId)}).ContentId
              ContentPath             = ($Temp_DT_XML_Sub.Installer.Contents.Content | Where-Object {$_.ContentId -eq ($Temp_DT_XML_Sub.Installer.UninstallAction.Contents.Content.ContentId)}).Location
              ContentFile             = ($Temp_DT_XML_Sub.Installer.Contents.Content | Where-Object {$_.ContentId -eq ($Temp_DT_XML_Sub.Installer.UninstallAction.Contents.Content.ContentId)}).File
            }
            Detection         = [ScriptDetection]@{
              Provider    = $Temp_DT_XML_Sub.Installer.DetectAction.Provider
              Context     = ($Temp_DT_XML_Sub.Installer.DetectAction.Args.Arg | Where-Object {$_.Name -eq "ExecutionContext"}).InnerText
              ScriptType  = $Trans_ScriptDetection_ScriptType[[int]($Temp_DT_XML_Sub.Installer.DetectAction.Args.Arg | Where-Object {$_.Name -eq "ScriptType"}).InnerText]
              ScriptBody  = ($Temp_DT_XML_Sub.Installer.DetectAction.Args.Arg | Where-Object {$_.Name -eq "ScriptBody"}).InnerText
              RunAs32Bit  = if (($Temp_DT_XML_Sub.Installer.InstallAction.Args.Arg | Where-Object {$_.Name -eq "RunAs32Bit"}).InnerText -eq "true") {$true} else {$false}
            }
          }
        }
      }
      else {
        Write-HostFormat -Message "Status: Skipped" -Type INFO -Indent 6
      }
      Write-HostFormat -Message "Status: Success" -Type INFO -Indent 5

    }
    catch {
      Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1606
    }
    finally {
      # Cleanup Variables
      Remove-Variable -Name "Item" -ErrorAction SilentlyContinue
      # Remove-Variable -Name "Temp_*" -ErrorAction SilentlyContinue
    }
  }

	Write-HostFormat -Message "- Complete" -Type INFO -Indent 2 -NewLines 1

#EndRegion Data Gather
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Execution
#   Error Range: 1700 - 1799
#--------------------------------------------------------------------------------------------
#Region Execution

  Write-HostFormat -Message "Execution" -Type INFO -Indent 1

  foreach ($Item in ($Dataset_Applications | Where-Object -FilterScript {$_.Include -eq $true})) {
    Write-HostFormat -Message "- $($Item.Application.Manufacturer) - $($Item.Application.LocalizedDisplayName) - $($Item.Application.SoftwareVersion)" -Type INFO -Indent 2
    $Item.Status = "In Progress"

    # Prepare Output Folder`
    Write-HostFormat -Message "Prepare Output Folder" -Type INFO -Indent 4

    try {
      if ($Item.Actions.Install.Content -in "", $null, $false) {
        Write-HostFormat -Message "Status: Skipped, No Content" -Type INFO -Indent 5
      }
      else {
        Write-HostFormat -Message "Path: $($Item.IntunePrepTool.Output)" -Type DEBUG -Indent 5
        if (Test-Path -Path "filesystem::$($Item.IntunePrepTool.Output)") {
          Write-HostFormat -Message "Status: Exists" -Type INFO -Indent 5
        }
        else {
          if ($Param_Mode -eq "Analyze") {
            Write-HostFormat -Message "Status: Skipped because mode is set to Analyze" -Type INFO -Indent 5
          }
          elseif ($Param_Mode -eq "Execute") {
            New-Item -Path ($Item.IntunePrepTool.Output | Split-Path -Parent) -Name ($Item.IntunePrepTool.Output | Split-Path -Leaf) -ItemType Directory | Out-Null
            Write-HostFormat -Message "Status: Created" -Type INFO -Indent 5
          }
        }
      }
    }
    catch {
      $Item.Status = "Error: Preparing Output Folder"
      Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1701
    }

    # Prepare Content
    Write-HostFormat -Message "Prepare Content" -Type INFO -Indent 4

    try {
      if ($Item.Actions.Install.Content -in "", $null, $false) {
        Write-HostFormat -Message "Status: Skipped, No Content" -Type INFO -Indent 5
      }
      else {
        if (([System.IO.Path]::GetFileNameWithoutExtension($Item.IntunePrepTool.File) + ".intunewin") -eq (Get-ChildItem -LiteralPath $Item.IntunePrepTool.Output -Filter "*.intunewin")) {
          $Item.IntunePrepTool.Status = "Exists"
          Write-HostFormat -Message "Status: Exists" -Type INFO -Indent 5
        }
        else {
          if ($Param_Mode -eq "Analyze") {
            Write-HostFormat -Message "Status: Skipped because mode is set to Analyze" -Type INFO -Indent 5
          }
          elseif ($Param_Mode -eq "Execute") {
            
          }
          Write-Host ("          Command: &`"{0}`" -c `"{1}`" -s `"{2}`" -o `"{3}`" -q" -f $Param_IntunePrepToolPath, $Item.IntunePrepTool.Source, $Item.IntunePrepTool.File, $Item.IntunePrepTool.Output)
          Write-HostFormat -Message "" -Type INFO -Indent 
          # $Result = & $Param_IntunePrepToolPath -c "$($Item.IntunePrepTool.Source)" -s "$($Item.IntunePrepTool.File)" -o "$($Item.IntunePrepTool.Output)" -q
          $Item.IntunePrepTool.Status = "Created"
          Write-Host "          Status: Created"
          Write-HostFormat -Message "" -Type INFO -Indent 
        }
      }
    }
    catch {
      $Item.Status = "Error: Preparing Content"
      Write-HostFormat -ErrorObject $PSItem -Type FATAL -Indent 5 -ExitCode 1702
    }
  }

  # # Create Intune Applications
  # Write-Host "    - Create Intune Applications"

  # foreach ($Item in ($Dataset_Applications | Where-Object -FilterScript {$_.Include -eq $true})) {
  #   try {
  #     Write-Host "        $($Item.Application.Manufacturer) - $($Item.Application.LocalizedDisplayName) - $($Item.Application.SoftwareVersion)"
  #     Write-Host "          Create Request Body"


  #     Write-Host "          Send Request"


  #     Write-Host "          Status: Success"
  #   }
  #   catch {
  #     Write-vr_ErrorCode -Code 1702 -Exit $true -Object $PSItem
  #   }
  # }
  # Write-Host "        Status: Success"





  # .\IntuneWinAppUtil.exe -c "C:\Users\V00004255.SA\Downloads\Source" -s "C:\Users\V00004255.SA\Downloads\Source\setup.exe" -o "C:\Users\V00004255.SA\Downloads\Output"




















	# # [StepName]
  # Write-Host "    - [StepName]"

  # try {

  #   Write-Host "        Status: Success"
  # }
  # catch {
  #   Write-vr_ErrorCode -Code 17XX -Exit $true -Object $PSItem
  # }

	# # [StepName]
  # Write-Host "    - [StepName]"

  # foreach ($Item in (Get-Variable -Name "Path_*")) {
  #   try {
  #     Write-Host "        $($Item.Name)"
  #     Write-Host "          Status: Success"
  #   }
  #   catch {
  #     Write-vr_ErrorCode -Code 17XX -Exit $true -Object $PSItem
  #   }
  # }
  # Write-Host "        Status: Success"

	# Determine Script Result
  $Meta_Script_Result = $true,"Success"

	Write-HostFormat -Message "- Complete" -Type INFO -Indent 2 -NewLines 1

#EndRegion Execution
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Output
#   Error Range: 1800 - 1899
#--------------------------------------------------------------------------------------------
#Region Output

	Write-Host "  Output"

  # Output Datasets
  Write-Host "    - Output Datasets"

  foreach ($Item in (Get-Variable -Name "Dataset_*")) {
    try {
      Write-Host "        $($Item.Name)"
      Write-Host "        Path: $($Param_OutputDir)\$($Item.Name).json"
      $Item.Value | ConvertTo-Json | Out-File -FilePath "Filesystem::$($Param_OutputDir)\$($Item.Name).json"
      Write-Host "        Status: Success"
    }
    catch {
      Write-vr_ErrorCode -Code 1801 -Exit $true -Object $PSItem
    }
  }

	# [StepName]
  Write-Host "    - [StepName]"

  try {

    Write-Host "        Status: Success"
  }
  catch {
    Write-vr_ErrorCode -Code 18XX -Exit $true -Object $PSItem
  }

	Write-HostFormat -Message "- Complete" -Type INFO -Indent 2 -NewLines 1

#EndRegion Output
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Cleanup
#   Error Range: 1900 - 1999
#--------------------------------------------------------------------------------------------
#Region Cleanup

	Write-Host "  Cleanup"

	# Disconnect From Microsoft Graph
  Write-Host "    - Disconnect From Microsoft Graph"

  try {
    if (Get-MgContext) {
      $Result = Disconnect-MgGraph
      Write-Host "        Account: $($Result.Account)"
      Write-Host "        TenantId: $($Result.TenantId)"
      Write-Host "        ClientId: $($Result.ClientId)"
      Write-Host "        Status: Success"
    }
    else {
      Write-Host "          Status: No Connection Found"
    }
  }
  catch {
    Write-vr_ErrorCode -Code 1901 -Exit $true -Object $PSItem
  }

	Write-HostFormat -Message "- Complete" -Type INFO -Indent 2 -NewLines 1

#EndRegion Cleanup
#--------------------------------------------------------------------------------------------


#--------------------------------------------------------------------------------------------
# Footer
#--------------------------------------------------------------------------------------------
#Region Footer

	# Gather Data
  $Meta_Script_Complete_DateTime  = Get-Date
  $Meta_Script_Complete_TimeSpan  = New-TimeSpan -Start $Meta_Script_Start_DateTime -End $Meta_Script_Complete_DateTime

	# Output
  Write-Host "------------------------------------------------------------------------------"
  Write-Host "  Script Result: $($Meta_Script_Result[0])"
  Write-Host "  Script Started: $($Meta_Script_Start_DateTime.ToUniversalTime().ToString(`"yyyy-MM-dd HH:mm:ss`")) (UTC)"
  Write-Host "  Script Completed: $($Meta_Script_Complete_DateTime.ToUniversalTime().ToString(`"yyyy-MM-dd HH:mm:ss`")) (UTC)"
  Write-Host "  Total Time: $($Meta_Script_Complete_TimeSpan.Days) days, $($Meta_Script_Complete_TimeSpan.Hours) hours, $($Meta_Script_Complete_TimeSpan.Minutes) minutes, $($Meta_Script_Complete_TimeSpan.Seconds) seconds, $($Meta_Script_Complete_TimeSpan.Milliseconds) milliseconds"
  Write-Host "------------------------------------------------------------------------------"
  Write-Host "  End of Script"
  Write-Host "------------------------------------------------------------------------------"

#EndRegion Footer
#--------------------------------------------------------------------------------------------

Stop-Transcript
Return $Meta_Script_Result[0]